### ISSUE TITLE
Running --generate-answers-file FAILS if required fields are present

### ISSUE THREAD

**Issue by talkammer** [redhat-openstack/infrared#295]
Currently, when using infrared, if you try to create the --generate-answers-file <FILE> when you have a "required: yes" in your spec, it fails the creation of the answers file with:
ERROR   Required options are not set:

Expected behavior is that creating the answers file should precede the validation of the required fields.

That being said, using the "--from-file" should validate if the required fields are provided and if not, fail with the expected error above.

**Comment by ovorobio** [comment]
Hi Tal,

--generate-answers-file is not actually failing generating a file when required options are not set, file is created but ir throws an error message telling what options are not set but required. I've created a patch that comments required options in the answers file if they are not set so that '--from-file' is not failing an error while parsing answers file.

Here is the link: https://review.gerrithub.io/#/c/371653/
