### ISSUE TITLE
Mariadb has been broken in controller node 

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#296]
Hello,

I have setup 2 controller node with HA proxy through your playbook.
Mariadb has been broken in both node though configured with Galera cluster.

170728 18:32:31 mysqld_safe WSREP: Running position recovery with --log_error='/var/lib/mysql/wsrep_recovery.dleosx' --pid-file='/var/lib/mysql/controller-1.localdomain-recover.pid'
170728 18:32:31 [Warning] option 'open_files_limit': unsigned value 18446744073709551615 adjusted to 4294967295
170728 18:32:31 [Warning] option 'open_files_limit': unsigned value 18446744073709551615 adjusted to 4294967295
170728 18:32:31 [Warning] Could not increase number of max_open_files to more than 1024 (request: 4907)

Could you provide some solutions how do i recover this

**Comment by rhosqeauto** [comment]
Hi,
I'm sorry, but as far as I know, 2 controllers setup  isn't supported. You
need 3.
If you think this is not related, then I believe this is an Openstack bug
you may have to go through proper Red Hat channels to get support on this.

We might be able to help a little if you provide more details about your
hypervisor, the infrared commands you used, and maybe even the console
output

Regards
Yair

**Comment by coolpalani** [comment]
Hello Yair,

I believe this is not OpenStack related bugs.
For example in devstack, the cluster has to be re-initialized after the host is rebooted.

Please refer this url

https://docs.openstack.org/openstack-ansible/latest/contributor/quickstart-aio.html

need to run this ansible playbook 

openstack-ansible -e galera_ignore_cluster_state=true galera-install.yml

I have several times rebooted the controller host node and ran that above playbook for bring up Galera cluster.
in RedHat OpenStack infrared based project, we may be need to figure out same way make Galera cluster will be available after host node rebooted.

**Comment by obaranov** [comment]
Hi coolpalani, 

Can you please send us a list or IR commands (starting from provision stage) you are running and on what stage (or after what actions) you are getting that problem. In particular, do you manually reboot host node? 
Can you please also provide the openstack version your are trying to deploy. We need all that info to reproduce that issue and think on how we can resolve it. 

Thanks, 
Oleksii

**Comment by coolpalani** [comment]
Hello Oleksii,

I had used infrared playbook for setup RedHat OpenStack and it had been working as past 2 months without having problem.
Due to some reason, I was reboot the controller nodes without put the pacemaker cluster in maintenance mode.
once node come up, mysql isn't started due to node out of sync.
Finally today I followed this redhat articles steps https://access.redhat.com/solutions/1283463 and make a mariadb service as up and running. But redis service is still down.
Dashboards are able to access now.

**Comment by ovorobio** [comment]
Hi coolpalani.

This is expected behavior for galera cluster consisting only two nodes. Minimal amount of nodes required for HA is 3. When you rebooted one of your controller, galera database on another one got a 'split brain' and fall into read only mode. It was in this state till you fixed galera and returned back the second node. During this time all services that required database could behave unexpectedly and may fall into error state.

For correct HA testing please use 3 controllers, in that case galera is able to remain in operational state when one of the controller went down.

**Comment by coolpalani** [comment]
Hello Ovorobio,

I will try to make a backup of current workload and will build a HA OpenStack with 3 controller nodes.
could you bit explain, in 3 controller node setup how galera cluster will take care when one of node goes into out of sync.

**Comment by ovorobio** [comment]
Sure, when one of the nodes for some reason is out of sync the quorum votes is happening, and majority of remaining nodes are consider themselves as a so called 'Primary component' that is able to operate further since their amount is more than a half of amount of nodes that were originally in a cluster. You can check this link to get more info:

http://galeracluster.com/documentation-webpages/weightedquorum.html#id1
